In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("telecom_customer_churn_feature_engineering.csv")

In [2]:
#Date part exraction
df['signup_date'] = pd.to_datetime(df['signup_date'])

df['signup_year'] = df['signup_date'].dt.year
df['signup_month'] = df['signup_date'].dt.month
df['signup_day'] = df['signup_date'].dt.dayofweek
df[['signup_date','signup_year','signup_month','signup_day']].head()

  signup_date  signup_year  signup_month  signup_day
0  2019-01-01         2019             1           1
1  2019-01-02         2019             1           2
2  2019-01-03         2019             1           3
3  2019-01-04         2019             1           4
4  2019-01-05         2019             1           5

In [3]:
#Ratio feature
df['bill_to_income_ratio'] = (
    df['monthly_bill'] / df['monthly_income']
)

df[['monthly_bill','monthly_income','bill_to_income_ratio']].head()

   monthly_bill  monthly_income  bill_to_income_ratio
0       10049.0         57643.0              0.174332
1        2752.0         18207.0              0.151151
2        3155.0         13075.0              0.241300
3        5859.0         38890.0              0.150656
4        5106.0         17475.0              0.292189

In [4]:
#interaction feature
df['support_bill_interaction'] = (
    df['support_tickets'] * df['monthly_bill']
)
df[['support_tickets','monthly_bill','support_bill_interaction']].head()

   support_tickets  monthly_bill  support_bill_interaction
0                1       10049.0                   10049.0
1                2        2752.0                    5504.0
2                0        3155.0                       0.0
3                2        5859.0                   11718.0
4                0        5106.0                       0.0

In [5]:
df['feedback_length'] = df['customer_feedback'].str.len()

df[['customer_feedback','feedback_length']].head()

                        customer_feedback  feedback_length
0         Coverage is poor in my location               31
1  Billing issues occurred multiple times               38
2  Billing issues occurred multiple times               38
3            Customer support was helpful               28
4         Coverage is poor in my location               31

In [6]:
#keyword flag feature
df['complaint_flag'] = df['customer_feedback'].str.contains(
    'slow|poor|expensive|unrealiable|drops',
    case = False
).astype(int)

df[['customer_feedback','complaint_flag']].head()

                        customer_feedback  complaint_flag
0         Coverage is poor in my location               1
1  Billing issues occurred multiple times               0
2  Billing issues occurred multiple times               0
3            Customer support was helpful               0
4         Coverage is poor in my location               1