In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('dataFile.csv')
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

In [8]:
df_sorted = df.sort_values(by=['Price','Color'],ascending = [True,True])
df_sorted.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
17,18,Digital Tablet Router Printer Lite,Accept campaign every research test.,Vazquez-Smith,Health & Wellness,3,USD,732,4170125892616,LemonChiffon,10x10 cm,backorder,87
69,70,Compact Mouse Mouse Router Mini,Occur miss son Democrat happy.,Barry PLC,Smartwatches,5,USD,247,252926529077,PapayaWhip,10x10 cm,limited_stock,79
70,71,Premium Lock Mini Advanced,Three character traditional maybe.,"Elliott, Mcfarland and Duran",Automotive,12,USD,439,3997003361528,Plum,XS,pre_order,40
87,88,Silent Scanner Monitor Treadmill,Do interesting suggest agreement range admit r...,"Nichols, Howe and Miller",Health & Wellness,30,USD,728,1287056757693,Wheat,10x10 cm,pre_order,60